package Item_30.Example_02;

import java.util.function.UnaryOperator;

/**
 * @author Vasilii Serebrovskii
 * @version 1.0 (01.12.2025)
 */
public class ExampleApp {
    // Generic singleton factory pattern
    private static UnaryOperator<Object> IDENTITY_FN = (t) -> t;

    /*
    The cast of IDENTITY_FN to (UnaryFunction<T>) generates an unchecked cast warnings, as UnaryOperator<Object> is not a UnaryOperator<T> for every T.
    But the identity function is pecial: it returns its argument unmodified, so we know that it is typesafe to use it as a UnaryFunction<T>,
    whatever the value of T.
    Therefor, we can confidently suppress the unchecked cast warning generated by this cast.
     */
    @SuppressWarnings("unchecked")
    public static <T> UnaryOperator<T> identityFunction() {
        return (UnaryOperator<T>) IDENTITY_FN;
    }

    // Sample program to exercise generic singleton
    public static void main(String[] args) {
        String[] strings = {"jute", "hemp", "nylon "};
        UnaryOperator<String> sameString = identityFunction();
        for (String s: strings) {
            System.out.println(sameString.apply(s));
        }

        Number[] numbers = {1, 2.0, 3L};
        UnaryOperator<Number> sameNumber = identityFunction();
        for (Number n: numbers)
            System.out.println(sameNumber.apply(n));
    }
}
